### ISSUE TITLE
delSpan Pre-Processing Notes

### ISSUE THREAD

**Issue by nhammer514** [FrankensteinVariorum/collationWorkspace#18]
```xml
<delSpan rend="strikethrough" spanTo="#c57-0045.05"/>My voice  
<lb n="c57-0045__main__10"/> although harsh had nothin 
<mod sID="c57-0045__main__d4e8612"/>
   <mdel>k</mdel>
    <sga-add place="intralinear" sID="c57-0045__main__d4e8616"/>g <sga-add eID="c57-0045__main__d4e8616"/>
   <mod eID="c57-0045__main__d4e8612"/>  terrible in  
<lb n="c57-0045__main__11"/> it. 
<anchor xml:id="c57-0045.05"/>```

^ When we see pattern like this, XSLT/Python should generate longToken element to wrap around.

In regeneration, we will need to apply the changes to all collation chunks.

**Comment by ebeshero** [comment]
Also, just looking for `<delSpan spanTo="#id"/>....</anchor xml:id="id"/>`

to change the closing `<anchor>` into this:

`<delSpan anchor="id"/>`.


We want to wrap a `<longToken>` when the elements in between are anything other than just `<lb/>`.

Then output:

`<longToken><delSpan spanTo="#id"/>....</delSpan anchor="id"/></longToken>`

**Comment by ebeshero** [comment]
We have successfully changed all delSpan `<anchor>` elements into `<delSpan anchor="..."/>`. Inspecting the results in the msColl files, there is *one* special case of complicated overlapping delSpans. I am pre-emptively wrapping this special passage from c56 in a longToken "by hand" because it is very unlike any of the other delSpan passages. (In other passages, if there are multiple `<delSpan>` elements together, they are nested. In this case, the delSpans overlap.)

```xml
<longToken type="longDel"><delSpan rend="strikethrough" spanTo="#c56-0009.02"/>and <lb n="c56-0009__Pt2__main__23"/>
   <delSpan rend="vertical_line" spanTo="#c56-0009.01"/>one evening<delSpan anchor="c56-0009.02"/> that I spent in town at the <lb n="c56-0009__Pt2__main__24"/>house of Clerval's father I <delSpan rend="strikethrough" spanTo="#c56-0009.03"/>heard
              that <lb n="c56-0009__Pt2__main__25"/>M<shi rend="sup">r</shi> — was lef at<delSpan anchor="c56-0009.03"/> met M. <del rend="strikethrough" xml:id="c56-0009__Pt2__main__d6e2518">O P</del> a proficient <lb n="c56-0009__Pt2__main__26"/>in Chemistry who left the company at <lb n="c56-0009__Pt2__main__27"/>an early hour to <del rend="strikethrough" xml:id="c56-0009__Pt2__main__d6e2526">h</del> give his lecture upon <lb n="c56-0009__Pt2__main__28"/>
   <w ana="start"/>tha<mod sID="c56-0009__Pt2__main__d6e2533"/>
   <mdel>n</mdel>
   <sga-add place="intralinear" sID="c56-0009__Pt2__main__d6e2537"/>t<w ana="end"/>
   <sga-add eID="c56-0009__Pt2__main__d6e2537"/>
   <mod eID="c56-0009__Pt2__main__d6e2533"/> science enquiring as he went out<delSpan anchor="c56-0009.01"/></longToken>
```

**Comment by ebeshero** [comment]
Also: let's add a pre-processing XSLT stage to the Python script to eliminate newline characters inside the special longToken `inlineVariationEvent` elements. These are: 
```py
inlineVariationEvent = ['head', 'del', 'mdel', 'add', 'note', 'longToken']
```
Doing this will mean we don't have to backspace when inputting longToken elements. The collation script process will do the backspacing for us (by replacing `\n` with ` ` in the text nodes of these elements) reducing potential for hand-typed error. This also definitely ensures that each of these elements is handled as a single longToken in the collation. This should eliminate a lot of kludgy backspacing by hand. 

(We can use the SaxonPy processor to handle this from within collation.py, now that we know how it works.)

**Comment by ebeshero** [comment]
@nhammer514 I determined we should NOT do this `<delSpan>...<anchor>` pre-processing back in the old collateXTesting repo, because we don't want to start over totally. If we do the work there, we'd be overwriting all the good `<longToken>` work we've done so far. Not worth it! 

Instead, we can write a simple XSLT file that runs in *this* collationWorkspace repo, just before the python script runs. The simple XSLT will: 
* alter the delSpan anchor elements without disturbing any `<longToken>` elements we've set already,
* give us a chance to remove newlines from inside the inlineVariationEvent elements listed above.

Here is the simple XSLT template rule we need to apply for handling the delSpan anchors:

```xml
 <!-- 2023-05-17 ebb and nlh: Adding handling for delSpan anchors only here. delSpan elements are used to cross over multiple lines and sometimes other deletions.
        Technically they should be a single complete token, representing a deletion event, but they can be complicated when they contain multiple modifications inside.
        Because these do not start out as matching element pairs, we are simply matching them here so we can (we hope) process them later as a completely deleted passage.
        We change the anchor into a matching delSpan with an anchor attribute, intended to substitute for the original <anchor> element so it's distinct from other <anchor> elements
        less meaningful to the collation. 
        
        <delSpan spanTo="#id"/>......<delSpan anchor="id"/>
     -->
    <xsl:template match="anchor[@xml:id = preceding::delSpan/substring-after(@spanTo, '#')]">
           <delSpan anchor="{@xml:id}"/>
    </xsl:template>    
```
